plugins {
	id "dev.architectury.loom-no-remap" version "1.14-SNAPSHOT" apply false
	id "architectury-plugin" version "3.5-SNAPSHOT"
	id 'com.gradleup.shadow' version '8.3.6' apply false
}

architectury {
	minecraft = project.minecraft_version
}

allprojects {
	group = rootProject.maven_group
	version = rootProject.mod_version

	repositories {
		maven {
			name = 'ParchmentMC'
			url = 'https://maven.parchmentmc.org'
		}
		maven {
			name = 'TerraformersMC'
			url = "https://maven.terraformersmc.com/releases/"
		}
		maven {
			name = 'NeoForged'
			url = 'https://maven.neoforged.net/releases'
		}
		mavenCentral()
	}
}

subprojects {
	apply plugin: "dev.architectury.loom-no-remap"
	apply plugin: 'architectury-plugin'
	apply plugin: 'maven-publish'

	version = ""

	base {
		archivesName = "${rootProject.archives_name}-${rootProject.mod_version}-${project.name}-${rootProject.minecraft_version}"
	}

	tasks.withType(Jar).configureEach {
		archiveVersion.set("")

		if (name == "sourcesJar") {
			archiveClassifier.set("sources")
		}
	}

	loom {
		silentMojangMappingsLicense()

		runs {
			client {
				client()
				property "easegui.debug", "true"
			}
			server {
				server()
				property "easegui.debug", "true"
			}
		}
	}

	dependencies {
		minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
	}

	java {
		withSourcesJar()
		sourceCompatibility = JavaVersion.VERSION_25
		targetCompatibility = JavaVersion.VERSION_25
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.release = 25
	}

	processResources {
		def replaceProperties = [
				minecraft_version : rootProject.minecraft_version,
				mod_version : rootProject.mod_version,
				fabric_loader_version : rootProject.fabric_loader_version,
				fabric_api_version : rootProject.fabric_api_version,
				mod_menu_version : rootProject.mod_menu_version,
				neoforge_version : rootProject.neoforge_version
		]

		inputs.properties replaceProperties

		filesMatching(["fabric.mod.json", "META-INF/neoforge.mods.toml"]) {
			expand replaceProperties
		}
	}

	publishing {
		publications {
			mavenJava(MavenPublication) {
				artifactId = base.archivesName.get()
				from components.java
			}
		}
	}
}