plugins {
    id 'com.gradleup.shadow'
}

loom {
    forge {
        mixinConfig "easegui.mixins.json"
    }
}

architectury {
    platformSetupLoomIde()
    forge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    forge "net.minecraftforge:forge:$rootProject.forge_version"

    implementation(include("io.github.llamalad7:mixinextras-forge:0.4.1"))

    modLocalRuntime "dev.emi:emi-forge:${rootProject.emi_version}"

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionForge')
}

processResources {
    def replaceProperties = [
            mod_version : rootProject.mod_version,
            minecraft_version : rootProject.minecraft_version,
            forge_version : rootProject.forge_version
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set(shadowJar.archiveFile)
}